name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Or your preferred version

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: https://github.com/jaypatel0112/JayPatel
        with:
          folder: build # The folder containing the build output
          branch: gh-pages # The branch to deploy to
          token: ${{ secrets.GITHUB_TOKEN }}